# _config.yml
title: "Sagar Setru"
# description: "My personal website"

# Use the single-column Modernist theme
remote_theme: pages-themes/modernist@v0.2.0

plugins:
  - jekyll-remote-theme

# Turn off “edit” links
show_edit_on_github: false
edit_links: false
edit_url: false
