# _config.yml
title: "Sagar Setru"
# description: "My personal website"

remote_theme: dsusca/no-style-please
plugins:
  - jekyll-remote-theme

# Turn off “edit” links
show_edit_on_github: false
edit_links: false
edit_url: false
